channels:
- conda-forge
- defaults
dependencies:
- python=3.9.7
- git=2.34.1
- pip
- cfgrib
- eccodes=2.24.2
- numpy
- xarray
- pytest
- psy-view
- psy-reg
- cartopy
- pip:
  - "git+https://github.com/C2SM/ICON-data-processing@v0.1.6#egg=ICON-data-processing"
- pre-commit
