channels:
- conda-forge
- defaults
dependencies:
- python=3.9.7
- git=2.34.1
- pip
- cfgrib
- eccodes=2.24.2
- numpy
- xarray
- pytest
- psy-view
- psy-reg
- cartopy
- pip:
  - "git+https://github.com/C2SM/icon-vis-utils@v0.1.0#egg=icon-vis-utils"
- pre-commit
