channels:
- conda-forge
- defaults
dependencies:
- python=3.9.14
- git=2.34.1
- pip
- cfgrib>=0.9.9.1
- eccodes=2.25.0
- numpy
- xarray
- pytest
- psy-view
- psy-reg
- cartopy
- earthkit-data
- pip:
  - git+https://github.com/C2SM/iconarray@v0.3.0
- pre-commit
