channels:
- conda-forge
- defaults
dependencies:
- python=3.9.7
- git=2.34.1
- pip
- cfgrib
- eccodes=2.24.2
- numpy
- xarray
- pytest
- psy-view
- psy-reg
- cartopy
- pip:
  - git+https://github.com/C2SM/iconarray@v0.1.21#egg=iconarray
- pre-commit
