name: ci

on:
  push:
    branches:
    - '*'

  pull_request:
    branches:
    - '*'

env:
  CACHE_NUMBER: 0  # increase to reset cache manually

jobs:
  build:

    strategy:
      matrix:
        include:
        - os: ubuntu-latest
          label: linux-64
          prefix: /usr/share/miniconda3/envs/my-env
    name: unittests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup Mambaforge
      uses: conda-incubator/setup-miniconda@v2
      with:
        miniforge-variant: Mambaforge
        miniforge-version: latest
        activate-environment: my-env
        use-mamba: true

    - name: Set cache date
      run: echo "DATE=$(date +'%Y%m%d')" >> $GITHUB_ENV

    - uses: actions/cache@v2
      with:
        path: /usr/share/miniconda3/envs/my-env
        key: linux-64-conda-${{ hashFiles('env/environment.yml') }}-${{ env.DATE }}-${{ env.CACHE_NUMBER }}
      id: cache

    - name: Update environment
      run: mamba env update -n my-env -f env/environment.yml
      if: steps.cache.outputs.cache-hit != 'true'

    - name: Run tests
      shell: bash -l {0}
      run: pytest ./iconarray/tests/fast_tests.py
